# примеры API-запросов

@baseUrl = http://localhost:8000/api
@token1 = a5d9f2a1a65cd98cc5b38b84519d548f25b54489
@token2 = c3a6ba52b3ca9c7f6aed7d96068cf42634857323
# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token {{token1}}

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/9/
Content-Type: application/json
Authorization: Token {{token1}}

{
  "status": "OPEN"
}

###

# попытка удалить объявление
DELETE  {{baseUrl}}/advertisements/2/
Content-Type: application/json
Authorization: Token {{token1}}

###

# попытка поменять чужое объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token {{token2}}

{
  "status": "OPEN"
}

###

# попытка удалить объявление
DELETE  {{baseUrl}}/advertisements/2/
Content-Type: application/json
Authorization: Token {{token2}}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
