# примеры API-запросов

@baseUrl = http://localhost:8000/api
@token1 = ac985e53e39ce8c9eb3c3ab608a2e2e23117f638
@token2 = c3a6ba52b3ca9c7f6aed7d96068cf42634857323
# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token {{token1}}

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token {{token1}}

{
  "status": "CLOSED"
}

###

# попытка удалить объявление
DELETE  {{baseUrl}}/advertisements/2/
Content-Type: application/json
Authorization: Token {{token1}}

###

# попытка поменять чужое объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token {{token2}}

{
  "status": "OPEN"
}

###

# попытка удалить объявление
DELETE  {{baseUrl}}/advertisements/2/
Content-Type: application/json
Authorization: Token {{token2}}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
