# Generated by Django 4.1.4 on 2022-12-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_articletag_articles_alter_articletag_scopes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletag',
            old_name='articles',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='articletag',
            old_name='scopes',
            new_name='scope',
        ),
    ]
