# Generated by Django 4.1.4 on 2022-12-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_rename_articles_articletag_article_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleTag',
            new_name='ArticleScope',
        ),
        migrations.RenameField(
            model_name='articlescope',
            old_name='scope',
            new_name='tag',
        ),
    ]
